name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Unzip project
        run: unzip novalive-demo-with-entrance.zip -d app

      - name: Build with Gradle
        working-directory: app
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: NovaLive-APK
          path: app/app/build/outputs/apk/debug/app-debug.apk
